### ISSUE TITLE
GSAD error with Apache reverse proxy

### ISSUE THREAD

**Issue by cybermcm** [Atomicorp/gvm#6]
I'm trying to setup OpenVAS with an Apache revese proxy (also a docker image):
```
openvas:
  container_name: openvas
  environment:
   - OV_PASSWORD=xxx
   #- OV_UPDATE=yes
  image: atomicorp/openvas:latest
  networks:
   - compose
  restart: always
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /opt/openvas/:/var/lib/openvas/mgr
```
If I want to connect via browser I get this warning and no connection:
```
gsad main:WARNING:2018-12-23 21h39.31 utc:315: MHD: Error: received handshake message out of context
```
I read something about ALLOW_HEADER_HOST for gsad but this doesn't seem to be a viable option.
Any ideas?
